name: "Run Docs CD with UV"

on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build-deploy-docs:
    if: github.repository == 'jinhonglin-ryan/deep-searcher'
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    permissions:
      contents: write
