name: "Run Docs CD with UV"

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build-deploy-docs:
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    permissions:
      contents: write
